Make it a bit more robust by checking version first

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -15,6 +15,12 @@ else
  VERSION=$1
 fi
 
+KNOWNVERSION=`echo "3 4 0w" | grep $VERSION`
+if [ "$KNOWNVERSION" == "" ]; then
+ echo "Unsupported version $VERSION, aborting"
+ exit 1
+fi
+
 BRDIR=`./brdir $VERSION`
 echo "Building in $BRDIR"
 
